# Generated by Django 3.1.3 on 2020-11-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='office_hours',
            new_name='office_hours',
        ),
    ]
