# Generated by Django 3.1.2 on 2020-12-16 21:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='user',
        ),
        migrations.AddField(
            model_name='section',
            name='days',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.instructor'),
        ),
        migrations.AddField(
            model_name='section',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.ta'),
        ),
        migrations.AddField(
            model_name='section',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ta',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.course'),
        ),
        migrations.AlterField(
            model_name='ta',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='SyllabusPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_text', models.CharField(max_length=400)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syllabus.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='policies',
            field=models.ManyToManyField(to='syllabus.SyllabusPolicy'),
        ),
    ]
