# Generated by Django 3.1.3 on 2020-11-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_course_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ta',
            old_name='office_hours',
            new_name='office_hours',
        ),
    ]
